name: ArsyaCustomRTP
version: 1.0.0
main: me.arsyadev.customrtp.CustomRTPPlugin
api-version: '1.20'
author: ArsyaDev

depend: [Vault]
softdepend: [PlaceholderAPI]

commands:
  customrtp:
    description: RTP resource dengan biaya persen
    usage: /customrtp <overworld|nether|end|reload|givevoucher>

permissions:
  customrtp.admin:
    description: Reload plugin CustomRTP
    default: op

  customrtp.bypasscost:
    description: Bypass biaya masuk resource world
    default: op

  customrtp.givevoucher:
    description: Memberi voucher resource
    default: op
